### ISSUE TITLE
评论按钮只能显示两位数，100以上就被切割了

### ISSUE THREAD

**Issue by yyx290799684** [RedrockMobile/CyxbsMobile_Android#23]
![qq 20160509122207](https://cloud.githubusercontent.com/assets/11473783/15103679/c358831e-15e0-11e6-8a41-afc6f5f19341.png)
![qq 20160509122216](https://cloud.githubusercontent.com/assets/11473783/15103680/c35a2f16-15e0-11e6-9b12-9211143078d8.png)

**Comment by MathiasLuo** [comment]
https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgetmsgimg?&MsgID=8362633688016282439&skey=%40crypt_d6b7a87e_5b010e91e2569dc616cdf63eb730227e&type=slave

**Comment by MathiasLuo** [comment]
![image](https://cloud.githubusercontent.com/assets/10219741/15110763/5e799e12-1615-11e6-92a7-f0f111ee10d6.png)
