### ISSUE TITLE
摇一摇~~（优先级低）

### ISSUE THREAD

**Issue by yyx290799684** [RedrockMobile/CyxbsMobile_Android#26]
![qq 20160509122905](https://cloud.githubusercontent.com/assets/11473783/15103739/a4366b26-15e1-11e6-9ef4-f3ca1b1b8bcb.png)

**Comment by Stormouble** [comment]
优先级低？

**Comment by yyx290799684** [comment]
重点保障社区，这个没啥人用



发自我的小米手机

WLX <notifications@github.com>编写：

优先级低？

---

**Comment by Stormouble** [comment]
OK. Fixed
