### ISSUE TITLE
掌邮多久能回复使用

### ISSUE THREAD

**Issue by NNanfeng** [RedrockMobile/CyxbsMobile_Android#305]
如题

**Comment by 985892345** [comment]
学校会断服务直到24号，我们内部还要整改应用，有很多功能会下架，所以预计要11月中期了

**Comment by NNanfeng** [comment]
是不是只要是有关数据爬取的都会下架哇

**Comment by 985892345** [comment]
对

**Comment by NNanfeng** [comment]
课表查询都会下？

**Comment by NNanfeng** [comment]
那也太那啥了吧

**Comment by 985892345** [comment]
课表接口要到了，但学校只给了我们课表接口（

**Comment by NNanfeng** [comment]
空教室查询？

**Comment by 985892345** [comment]
无

**Comment by NNanfeng** [comment]
。。。。。。。学校的决策是否有点不近人情了

**Comment by 985892345** [comment]
但这些可以自己去爬
![0ADC2018](https://user-images.githubusercontent.com/62180145/197389702-3f69d736-66e3-4b80-ab60-95e088fb3d2b.png)

**Comment by 985892345** [comment]
> 。。。。。。。学校的决策是否有点不近人情了

我也想说，目前移动部门都在摆烂了

**Comment by NNanfeng** [comment]
还让🐎

**Comment by 985892345** [comment]
主要是移动这边不能给上面带来什么利益，他们想要的能给他们宣传的部门，比起移动端，上面更喜欢前端（

**Comment by NNanfeng** [comment]
这是可以说的吗

**Comment by NNanfeng** [comment]
说实话 学校领导不考虑大家的体验 直接下线，连提前预警都没说啊

**Comment by 985892345** [comment]
其实也有我们的问题，以前很多数据都是爬的，动了那边xinxihuaban的蛋糕

**Comment by NNanfeng** [comment]
那他们不给接口 只有自己爬啊
没办法的事啊

**Comment by NNanfeng** [comment]
你要不要把issue删一删 学校会不会查到有什么事情哇

**Comment by 985892345** [comment]
之后掌邮更多会做一些独立的业务了，想做学校的已有的有点难了

**Comment by NNanfeng** [comment]
http://172.20.3.47:8016/ksh/Z_KSH_index/index.html   这个可以看看 加在掌邮里还挺有趣的

**Comment by 985892345** [comment]
> http://172.20.3.47:8016/ksh/Z_KSH_index/index.html 这个可以看看 加在掌邮里还挺有趣的

如果是学校的资源，我们都只能去要接口，不能去爬

**Comment by NNanfeng** [comment]
> > http://172.20.3.47:8016/ksh/Z_KSH_index/index.html 这个可以看看 加在掌邮里还挺有趣的
> 
> 如果是学校的资源，我们都只能去要接口，不能去爬

。。。。。。。。 这也太。。。。

**Comment by 985892345** [comment]
新版已恢复服务
