### ISSUE TITLE
热门动态下滑太快时，item的长度会改变，造成卡顿

### ISSUE THREAD

**Issue by haruue** [RedrockMobile/CyxbsMobile_Android#38]
在“热门动态”中，下滑太快时，item 的长度会随着图片的加载而改变，造成卡顿并影响用户体验。可以考虑使用固定长度的 ImageView 和占位图（类似于QQ）。

**Comment by simonla** [comment]
或者先获取到尺寸信息。。。不过要web帮帮忙了。。。

**Comment by haruue** [comment]
我觉得不需要尺寸信息，缩略图反正也显示不完整，获取有没有图再放个固定大小的占位图就好吧。
