### ISSUE TITLE
缺失文件跑不起来用的是develop分支

### ISSUE THREAD

**Issue by youlongxifeng** [RedrockMobile/CyxbsMobile_Android#387]
Could not read script '/Users/CyxbsMobile_Android/build-logic/secret/secret.gradle' as it does not exist.

**Comment by 985892345** [comment]
你好，该项目因为是学校内的项目，所以跟密钥相关的文件不能共享，但是如果能看懂 build_logic 的逻辑的话，其实是可以修改部分逻辑跑起来的
