### ISSUE TITLE
缺少文件，这个项目可以跑起来吗

### ISSUE THREAD

**Issue by youlongxifeng** [RedrockMobile/CyxbsMobile_Android#450]
.gitignore 不提交 secret.gradle

/CyxbsMobile_Android/build-logic/secret/secret.gradle' as it does not exist.

line: 1

An exception occurred applying plugin request [id: 'module-manager']
> Failed to apply plugin 'app'.

**Comment by 985892345** [comment]
本项目由于是校内项目，并没有完全开源
如果想查看本项目的架构设计的话，可以参考我单独写的开源项目（架构基本一样，但是没有业务模块）：https://github.com/VegetableChicken-Group/WanAndroid_Multi
后续会考虑设置成不需要密钥文件也能跑

**Comment by 985892345** [comment]
目前已经提交最新的commit到dev了，可以不需要secrect就可以编译，还有问题的话可以加群讨论：
![e6aed4c1dafe141ab0f3a05ee456fcf2](https://github.com/RedrockMobile/CyxbsMobile_Android/assets/62180145/5f94ca51-bb3f-43b6-9189-d7463e668d18)
